### ISSUE TITLE
Improve Documentation for Tamper Chrome

### ISSUE THREAD

**Issue by sirdarckcat** [google/tamperchrome#13]
Many users give the extension poor scoring in the webstore because they don't understand they need to install two extensions.

We should improve the text in the installation screen, and potentially even add translations so it is more clear what is going on.

**Comment by eliyastein** [comment]
@sirdarckcat - Feel free to assign to me if you want, since I've made some cosmetic changes already. I can make the "Could not find Tamper Chrome application" screen stand out a little bit more. I think the text is too small and folks don't take take the time to digest the instructions and instead assume "Oh, there's an error so I'm moving on."

**Comment by sirdarckcat** [comment]
That would be awesome, thanks @eliyastein

**Comment by sirdarckcat** [comment]
Thanks @eliyastein do you plan to make any more changes?

**Comment by eliyastein** [comment]
Happy to make more changes if you have anything to suggest.

**Comment by sirdarckcat** [comment]
Nope, just checking to see if I can make a cut for the next version of the
extension :-)
